database:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  db_default: ${POSTGRES_DB}

  db_accm: "db_accm" # accident corporel circulation millésimé


sqlfile:
  file_1: "test_req.sql"
  
